### ISSUE TITLE
Wiki links lead to raw markdown rather than pages

### ISSUE THREAD

**Issue by JordanDChappell** [JordanDChappell/CSharp.Mongo.Migration#24]
Links in the generated API documentation incorrectly lead to raw markdown view rather than anchors in the API page

**Comment by yoshifp** [comment]
@JordanDChappell it looks like this can be achieved with the `RemoveFileExtensionFromUrl` property set to `true` in the configuration file, which the default one would be `DefaultDocumentation.json` in the project folder, and I can't see one in this project.

Their documentation doesn't provide a 'tool' argument for this option which makes it more difficult to use with the current Github workflow, if you want to keep the repo clean, the workflow could write out a config file temporarily or the path can be set in the `.csproj` file.

However, looking at the [DefaultDocumentation](https://github.com/Doraku/DefaultDocumentation) repo, they aren't using the `wiki` feature of Github, and are instead just loading their documentation pages via the `Code` tab/interface instead.

What are your thoughts on how to proceed with addressing this issue?


---

Note, while fixing this issue, we should check all links as I noticed some others are broken too, including:
- [MongoDB.Driver.IMongoCollection](https://docs.microsoft.com/en-us/dotnet/api/MongoDB.Driver.IMongoCollection)
- [MongoDB.Driver.IMongoDatabase](https://docs.microsoft.com/en-us/dotnet/api/MongoDB.Driver.IMongoDatabase) 
- [MongoDB.Bson.ObjectId](https://docs.microsoft.com/en-us/dotnet/api/MongoDB.Bson.ObjectId) 
 
It looks like it is an issue with references to non-Microsoft libraries, the documentation is trying to send us to Microsoft docs instead.

**Comment by JordanDChappell** [comment]
> @JordanDChappell it looks like this can be achieved with the `RemoveFileExtensionFromUrl` property set to `true` in the configuration file, which the default one would be `DefaultDocumentation.json` in the project folder, and I can't see one in this project.
> 
> Their documentation doesn't provide a 'tool' argument for this option which makes it more difficult to use with the current Github workflow, if you want to keep the repo clean, the workflow could write out a config file temporarily or the path can be set in the `.csproj` file.
> 
> However, looking at the [DefaultDocumentation](https://github.com/Doraku/DefaultDocumentation) repo, they aren't using the `wiki` feature of Github, and are instead just loading their documentation pages via the `Code` tab/interface instead.
> 
> What are your thoughts on how to proceed with addressing this issue?
> 
> Note, while fixing this issue, we should check all links as I noticed some others are broken too, including:
> 
>     * [MongoDB.Driver.IMongoCollection](https://docs.microsoft.com/en-us/dotnet/api/MongoDB.Driver.IMongoCollection)
> 
>     * [MongoDB.Driver.IMongoDatabase](https://docs.microsoft.com/en-us/dotnet/api/MongoDB.Driver.IMongoDatabase)
> 
>     * [MongoDB.Bson.ObjectId](https://docs.microsoft.com/en-us/dotnet/api/MongoDB.Bson.ObjectId)
> 
> 
> It looks like it is an issue with references to non-Microsoft libraries, the documentation is trying to send us to Microsoft docs instead.

@yoshifp I think that we should add a configuration file to the repository which includes the `RemoveFileExtensionFromUrl` property as well as the following that are currently arguments in the `docs.yml` file:
- `AssemblyPageName`
- `GeneratedAccessModifiers`
- `FileNameFactory`

**Note:** that `AssemblyFilePath` and `OutputDirectoryPath` should still be controlled by the actions runner as these are tightly coupled to the `docs.yml` workflow file.

Perhaps we could use external links to correctly link to the C# MongoDB library documentation? https://github.com/Doraku/DefaultDocumentation?tab=readme-ov-file#extern-links
