### ISSUE TITLE
Ensure duplicate versioned migrations are not present during location

### ISSUE THREAD

**Issue by JordanDChappell** [JordanDChappell/CSharp.Mongo.Migration#27]
If migrations with duplicate versions are provided to the runner via a locator then only one of the migrations will run (the first in the returned collection). Rather than silently skipping a migration, the locators should throw an exception to indicate that duplicates were detected.

## Requirements
- All migration locators should throw exceptions if duplicate versions are detected
- All duplicates should be detected, rather than just the first found, to avoid users fixing the first and then encountering the next
- Thrown exception should contain a message that describes all of the version strings that are duplicates

**Comment by yoshifp** [comment]
I've added a PR which implements this request.
